#include "globals.h"
#include "html.h"
#include <Arduino.h>

// F7: escape operator-controlled config values before interpolating them into an HTML
// attribute value. Centralized here (single call site edited if the escape set ever needs
// to change) instead of inlined at each of the 9 interpolation points below - a bare
// apostrophe typed into e.g. mqttServer would otherwise break out of the surrounding
// value='...' attribute and corrupt the rendered form. Order matters: '&' must be escaped
// first so it doesn't double-escape the entities produced for the other four characters.
static String htmlEscape(const String& s)
{
  String out;
  out.reserve(s.length());
  for (size_t i = 0; i < s.length(); i++) {
    char c = s[i];
    switch (c) {
      case '&':  out += "&amp;";  break;
      case '<':  out += "&lt;";   break;
      case '>':  out += "&gt;";   break;
      case '"':  out += "&quot;"; break;
      case '\'': out += "&#39;";  break;
      default:   out += c;        break;
    }
  }
  return out;
}

void handleRoot()
{
  String html;
  html += "<!DOCTYPE html>";
  html += "<html>";
  html += "<head>";
  html += "<meta charset='utf-8'>";
  html += "<meta name='viewport' content='width=device-width,initial-scale=1'>";
  html += "<style>";
  html += "*{box-sizing:border-box;}";
  html += "body{margin:0;padding:15px;background:#f4f7fb;font-family:Arial,Helvetica,sans-serif;color:#233244;}";
  html += ".card{max-width:980px;margin:auto;background:#fff;padding:24px;border-radius:18px;box-shadow:0 6px 20px rgba(0,0,0,.12);}";
  html += "h2{text-align:center;margin:0 0 16px;color:#1565C0;}";
  html += "h3{margin:22px 0 12px;color:#1565C0;border-bottom:2px solid #dbeafe;padding-bottom:6px;}";
  html += ".panel{background:#f8fbff;border:1px solid #dbeafe;border-radius:12px;padding:14px;margin-bottom:14px;}";
  html += ".sensor{border:1px solid #d8e3f0;border-radius:12px;padding:12px;margin-bottom:12px;background:#fbfdff;}";
  html += ".sensor-title{font-weight:bold;color:#0f4c81;margin-bottom:8px;}";
  html += ".row{display:flex;gap:12px;flex-wrap:wrap;margin-top:8px;}";
  html += ".field{flex:1;min-width:220px;}";
  html += ".field label,.single label{display:block;font-weight:bold;margin-bottom:6px;color:#556270;font-size:14px;}";
  html += ".field input,.single input{width:100%;padding:10px;border:1px solid #bfc9d6;border-radius:8px;font-size:15px;background:#fff;}";
  html += ".field input[type=checkbox]{width:auto;padding:0;margin-right:6px;transform:translateY(2px);}";
  html += ".single{margin:10px 0;}";
  html += "#d{background:#eef7ff;border-left:5px solid #2196F3;padding:12px;border-radius:10px;margin-bottom:18px;line-height:1.7;}";
  html += ".btn{width:100%;padding:14px;border:none;border-radius:10px;background:#2196F3;color:white;font-size:16px;font-weight:bold;cursor:pointer;margin-top:8px;}";
  html += ".btn:hover{background:#1976D2;}";
  html += ".note{font-size:13px;color:#64748b;margin-top:6px;}";
  html += ".tabs{display:flex;gap:8px;margin-bottom:16px;}";
  html += ".tab-btn{flex:1;padding:12px;border:none;border-radius:10px;background:#dbeafe;color:#1565C0;font-size:15px;font-weight:bold;cursor:pointer;}";
  html += ".tab-btn.active{background:#2196F3;color:#fff;}";
  html += ".tab-content{display:none;}";
  html += ".tab-content.active{display:block;}";
  html += "@media(max-width:600px){";
  html += ".card{padding:16px;}";
  html += ".field{min-width:100%;}";
  html += "h2{font-size:24px;}";
  html += "}";
  html += "</style>";
  html += "<script>";
  html += "function update(){";
  html += "fetch('/data')";
  html += ".then(r=>r.text())";
  html += ".then(t=>document.getElementById('d').innerHTML=t);";
  html += "}";
  html += "setInterval(update,100);";
  html += "window.onload=update;";
  html += "function showTab(name){";
  html += "document.querySelectorAll('.tab-content').forEach(e=>e.classList.remove('active'));";
  html += "document.querySelectorAll('.tab-btn').forEach(e=>e.classList.remove('active'));";
  html += "document.getElementById('tab-'+name).classList.add('active');";
  html += "document.getElementById('btn-'+name).classList.add('active');";
  html += "}";
  html += "</script>";
  html += "</head>";
  html += "<body>";
  html += "<div class='card'>";
  html += "<h2>NGHI LỄ CÂN TIM NEW</h2>";
  html += "<div id='d'>Loading...</div>";
  html += "<div class='tabs'>";
  html += "<button type='button' id='btn-general' class='tab-btn active' onclick=\"showTab('general')\">Cấu hình</button>";
  html += "<button type='button' id='btn-network' class='tab-btn' onclick=\"showTab('network')\">Mạng (Ethernet)</button>";
  html += "</div>";
  html += "<form action='/save' method='POST'>";
  html += "<div id='tab-general' class='tab-content active'>";
  html += "<div class='panel'>";
  html += "<h3>Sensor Configuration</h3>";
  for (int i = 0; i < DEVICE_NUM; i++) {
    html += "<div class='sensor'>";
    html += "<div class='sensor-title'>Sensor ";
    html += i + 1;
    html += "</div>";
    html += "<div class='row'>";
    html += "<div class='field'>";
    html += "<label><input type='checkbox' name='sensor";
    html += i;
    html += "' value='1'";
    html += sensorEnabled[i] ? " checked" : "";
    html += "> Enable this sensor for publish</label>";
    html += "</div>";
    html += "<div class='field'>";
    html += "<label>MIN Distance (mm)</label>";
    html += "<input name='min";
    html += i;
    html += "' value='";
    html += distanceMin[i];
    html += "'>";
    html += "</div>";
    html += "<div class='field'>";
    html += "<label>MAX Distance (mm)</label>";
    html += "<input name='max";
    html += i;
    html += "' value='";
    html += distanceMax[i];
    html += "'>";
    html += "</div>";
    html += "</div>";
    html += "</div>";
  }
  html += "<div class='note'>Enable only the sensors that should be required for the FULL condition.</div>";
  html += "</div>";
  html += "<div class='panel'>";
  html += "<h3>MQTT Settings</h3>";
  html += "<div class='single'>";
  html += "<label><input type='checkbox' name='mqtt_enable' value='1'";
  html += mqttEnabled ? " checked" : "";
  html += "> Enable MQTT</label>";
  html += "</div>";
  html += "<div class='single'>";
  html += "<label>MQTT IP</label>";
  html += "<input name='mqtt_ip' value='";
  html += htmlEscape(mqttServer);
  html += "'>";
  html += "</div>";
  html += "<div class='single'>";
  html += "<label>MQTT Port</label>";
  html += "<input name='mqtt_port' value='";
  html += mqttPort;
  html += "'>";
  html += "</div>";
  html += "<div class='single'>";
  html += "<label>Username</label>";
  html += "<input name='mqtt_user' value='";
  html += htmlEscape(mqttUser);
  html += "'>";
  html += "</div>";
  html += "<div class='single'>";
  html += "<label>Password (để trống = giữ nguyên)</label>";
  html += "<input type='password' name='mqtt_pass' placeholder='(giữ nguyên nếu để trống)'>";
  html += "</div>";
  html += "<div class='single'>";
  html += "<label>MQTT Topic</label>";
  html += "<input name='mqtt_topic' value='";
  html += htmlEscape(mqttTopic);
  html += "'>";
  html += "</div>";
  html += "<div class='single'>";
  html += "<label>FULL Message</label>";
  html += "<input name='mqtt_full' value='";
  html += htmlEscape(mqttFullValue);
  html += "'>";
  html += "</div>";
  html += "<div class='single'>";
  html += "<label>MISSING Message</label>";
  html += "<input name='mqtt_missing' value='";
  html += htmlEscape(mqttMissingValue);
  html += "'>";
  html += "</div>";
  html += "</div>";
  html += "<div class='panel'>";
  html += "<h3>OSC Settings</h3>";
  html += "<div class='single'>";
  html += "<label><input type='checkbox' name='osc_enable' value='1'";
  html += oscEnabled ? " checked" : "";
  html += "> Enable OSC output</label>";
  html += "</div>";
  html += "<div class='single'>";
  html += "<label>OSC IP</label>";
  html += "<input name='osc_ip' value='";
  html += htmlEscape(oscIp);
  html += "'>";
  html += "</div>";
  html += "<div class='single'>";
  html += "<label>OSC Port</label>";
  html += "<input name='osc_port' value='";
  html += oscPort;
  html += "'>";
  html += "</div>";
  html += "<div class='single'>";
  html += "<label>FULL Address</label>";
  html += "<input name='osc_address_full' value='";
  html += htmlEscape(oscAddressFull);
  html += "'>";
  html += "</div>";
  html += "<div class='single'>";
  html += "<label>FULL Value (int)</label>";
  html += "<input name='osc_value_full' value='";
  html += oscValueFull;
  html += "'>";
  html += "</div>";
  html += "<div class='single'>";
  html += "<label>MISSING Address</label>";
  html += "<input name='osc_address_missing' value='";
  html += htmlEscape(oscAddressMissing);
  html += "'>";
  html += "</div>";
  html += "<div class='single'>";
  html += "<label>MISSING Value (int)</label>";
  html += "<input name='osc_value_missing' value='";
  html += oscValueMissing;
  html += "'>";
  html += "</div>";
  html += "<div class='note'>Set different OSC addresses and values for FULL and MISSING states.</div>";
  html += "</div>";
  html += "<div class='panel'>";
  html += "<h3>Confirm Settings</h3>";
  html += "<div class='single'>";
  html += "<label>Confirm Time (ms)</label>";
  html += "<input name='confirm' value='";
  html += confirmTime;
  html += "'>";
  html += "</div>";
  html += "</div>";
  html += "<div class='panel'>";
  html += "<h3>Admin Auth</h3>";
  html += "<div class='single'>";
  html += "<label>Username</label>";
  html += "<input name='auth_user' value='";
  html += htmlEscape(authUser);
  html += "'>";
  html += "</div>";
  html += "<div class='single'>";
  html += "<label>Password (leave blank to keep current)</label>";
  html += "<input type='password' name='auth_pass' value=''>";
  html += "</div>";
  html += "<div class='note'>Required (HTTP Basic Auth) to Save Settings or use the Test buttons below. Change from the shipped default as soon as possible (F6).</div>";
  html += "</div>";
  html += "</div>"; // end tab-general
  html += "<div id='tab-network' class='tab-content'>";
  html += "<div class='panel'>";
  html += "<h3>Ethernet Static IP (fallback)</h3>";
  html += "<div class='single'>";
  html += "<label><input type='checkbox' name='eth_static_first' value='1'";
  html += ethUseStaticFirst ? " checked" : "";
  html += "> Ưu tiên IP tĩnh (bỏ qua DHCP)</label>";
  html += "</div>";
  html += "<div class='single'>";
  html += "<label>Static IP</label>";
  html += "<input name='eth_ip' value='";
  html += htmlEscape(ethStaticIp);
  html += "'>";
  html += "</div>";
  html += "<div class='single'>";
  html += "<label>Gateway</label>";
  html += "<input name='eth_gw' value='";
  html += htmlEscape(ethStaticGateway);
  html += "'>";
  html += "</div>";
  html += "<div class='single'>";
  html += "<label>Netmask</label>";
  html += "<input name='eth_mask' value='";
  html += htmlEscape(ethStaticNetmask);
  html += "'>";
  html += "</div>";
  html += "<div class='note'>Mặc định: thiết bị thử DHCP trước (tối đa 10s lúc boot), chỉ dùng IP tĩnh này khi không có DHCP server. Tick \"Ưu tiên IP tĩnh\" để dùng IP tĩnh ngay từ đầu, bỏ qua hoàn toàn 10s chờ DHCP - nếu IP/Gateway/Netmask nhập sai thì tự động lùi về thử DHCP như bình thường. Đổi giá trị ở đây không áp dụng ngay - cần reboot board (rút/cắm điện) để lần boot kế tiếp dùng cấu hình mới.</div>";
  html += "</div>";
  html += "</div>"; // end tab-network
  html += "<input class='btn' type='submit' value='SAVE SETTINGS'>";
  html += "</form>";
  html += "<div class='panel'>";
  html += "<h3>Test Settings</h3>";
  html += "<form action='/test_mqtt' method='POST' style='margin-bottom:10px;'>";
  html += "<input class='btn' type='submit' value='Test MQTT (FULL)'>";
  html += "</form>";
  html += "<form action='/test_osc' method='POST'>";
  html += "<input class='btn' type='submit' value='Test OSC (FULL)'>";
  html += "</form>";
  html += "</div>";
  html += "</div>";
  html += "</body>";
  html += "</html>";
  server.send(200, "text/html", html);
}
